### ISSUE TITLE
the plugin is not working on GoLand version 2023.3.4

### ISSUE THREAD

**Issue by MrAbdul** [templ-go/templ-jetbrains#18] opened 2024-03-05 17:28 UTC
Dear Templ team

i have templ version v0.2.598 installed and GoLand versuib 2023.3.4 
in my goland templ configuration the LSP path is pointing to C:\Users\pc\go\bin\templ.exe which exists.

but i am not getting any autocompletion for both html or go code inside templ files. its hard to code at this rate.

is my installation correct? is there a known bug?
i included some screenshots.

thank you for any support 

![not working example 2](https://github.com/templ-go/templ-jetbrains/assets/10082741/393b1f66-c1e8-47ce-aaec-f464fe7c5daa)
![not working example 3](https://github.com/templ-go/templ-jetbrains/assets/10082741/58835d9c-1887-46b8-8ed5-a99b766b9319)

**Comment by joerdav** [comment] 2024-03-05 17:32
Thanks for the report. I believe this is not a bug, looking at the screenshot you provided there is a syntax error indicated by the red underline, I believe this is due to a missing closing tag in both examples, templ cannot provide auto completion to a file with syntax errors.

**Comment by joerdav** [comment] 2024-03-05 17:32
I hope this helps.

**Closed by joerdav** 2024-03-05 17:32 UTC
