### ISSUE TITLE
Critical error. Can't open file at all

### ISSUE THREAD

**Issue by michaelhugi** [templ-go/templ-jetbrains#10] opened 2024-01-15 08:16 UTC
I can't open this templ file at all. It just won't open and just show the go file that it belongs to instead of opening the file in a tab:

```templ
package components

// Global name variable for example
var GlobalName string = ""

// Similar to YourNameIs, but uses the server's global name variable.
templ YourNameIsGlobal() {
	if GlobalName == "" {
		<p class="mb-5">Global name is empty</p>
	} else {
		<p>Global name is <span class="font-bold">{ GlobalName }</span></p>
	}
}

```

**Comment by a-h** [comment] 2024-02-02 11:00
I don't think you've provided enough information to troubleshoot this, or to help others understand what the issue is.

I'd consider taking an MP4 screen capture of what you're talking about, along with an explanation and posting it.

**Comment by joerdav** [comment] 2024-02-09 10:54
Closing this as insufficient information.

**Closed by joerdav** 2024-02-09 10:54 UTC
